# -*- coding: utf-8 -*-
"""project107.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14QBwwpReB4HMTK_wDRkIm0JtDzQX5Rj9
"""

import csv
import pandas as pd
import plotly.graph_objects as go

df=pd.read_csv("data107.csv")
#print(df)

student_df=df.loc[df["student_id"]=='TRL_abc']
print(student_df)

print(student_df.groupby("level",as_index=False)['attempt'].mean())
fig=go.Figure(go.Bar(x=['level 1','level 2','level 3','level 4'],
                     y=student_df.groupby("level")['attempt'].mean(),orientation='v'))
            
                     


fig.show()